-- MySQL Script generated by MySQL Workbench
-- ср, 02-лис-2016 00:14:44 +0200
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`companies` (
  `id_com` INT NOT NULL AUTO_INCREMENT,
  `name_com` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_com`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customers` (
  `id_cus` INT NOT NULL AUTO_INCREMENT,
  `name_cus` VARCHAR(45) NOT NULL,
  `id_com` INT NOT NULL,
  PRIMARY KEY (`id_cus`),
  INDEX `fk_customers_companies1_idx` (`id_com` ASC),
  CONSTRAINT `fk_customers_companies1`
    FOREIGN KEY (`id_com`)
    REFERENCES `mydb`.`companies` (`id_com`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`projects` (
  `id_project` INT NOT NULL AUTO_INCREMENT,
  `name_project` VARCHAR(45) NOT NULL,
  `id_cus` INT NULL,
  `id_com` INT NULL,
  INDEX `fk_projects_customers1_idx` (`id_cus` ASC),
  INDEX `fk_projects_companies1_idx` (`id_com` ASC),
  PRIMARY KEY (`id_project`),
  CONSTRAINT `fk_projects_customers1`
    FOREIGN KEY (`id_cus`)
    REFERENCES `mydb`.`customers` (`id_cus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projects_companies1`
    FOREIGN KEY (`id_com`)
    REFERENCES `mydb`.`companies` (`id_com`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`developers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`developers` (
  `id_dev` INT NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(45) NOT NULL,
  `lname` VARCHAR(45) NOT NULL,
  `age` VARCHAR(45) NOT NULL,
  `id_project` INT NULL,
  `id_company` INT NULL,
  PRIMARY KEY (`id_dev`),
  INDEX `fk_developers_projects_idx` (`id_project` ASC),
  INDEX `fk_developers_companies1_idx` (`id_company` ASC),
  CONSTRAINT `fk_developers_projects`
    FOREIGN KEY (`id_project`)
    REFERENCES `mydb`.`projects` (`id_project`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_developers_companies1`
    FOREIGN KEY (`id_company`)
    REFERENCES `mydb`.`companies` (`id_com`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`skills` (
  `id_skill` INT NOT NULL AUTO_INCREMENT,
  `name_skill` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_skill`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dev_skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dev_skills` (
  `id_skill` INT NOT NULL,
  `id_developer` INT NOT NULL,
  PRIMARY KEY (`id_skill`, `id_developer`),
  INDEX `fk_skills_has_developers_developers1_idx` (`id_developer` ASC),
  INDEX `fk_skills_has_developers_skills1_idx` (`id_skill` ASC),
  CONSTRAINT `fk_skills_has_developers_skills1`
    FOREIGN KEY (`id_skill`)
    REFERENCES `mydb`.`skills` (`id_skill`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_skills_has_developers_developers1`
    FOREIGN KEY (`id_developer`)
    REFERENCES `mydb`.`developers` (`id_dev`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


INSERT INTO `mydb`.`companies` (`name_com`) VALUES ('Terrasoft'),  ('Ubisoft');

INSERT INTO `mydb`.`customers` (`name_cus`, `id_com`)
VALUES ('GazMyas', (SELECT id_com FROM companies WHERE name_com = 'Ubisoft')),
('OKKO', (SELECT id_com FROM companies WHERE name_com = 'Ubisoft')),
('BOSH', (SELECT id_com FROM companies WHERE name_com = 'Terrasoft')),
('Melnitsa', (SELECT id_com FROM companies WHERE name_com = 'Terrasoft'));


INSERT INTO `mydb`.`projects` (`name_project`, `id_cus`, `id_com`) VALUES ('Bonus', '1', '2'),
('CommonRail', '2', '1'),
('Display', '3', '1'),
('Liniya', '4', '2');


INSERT INTO `mydb`.`developers` (`fname`, `lname`, `age`, `id_project`, `id_company`) VALUES ('Andrey', 'Polyakov', '19', '1', '2'),
('Petya', 'Golubcov', '26', '2', '1'),
('Misha', 'Zivakin', '23', '1', '2'),
('Katya', 'Kozlova', '29', '3', '1'),
('Illya', 'Nemkin', '32', '3', '1'),
('Kolya', 'Belkin', '20', '2', '1');

INSERT INTO `mydb`.`skills` (`name_skill`) VALUES ('SQL'),
('Java'),
('Php'),
('C++'),
('Hibernate');

INSERT INTO `mydb`.`dev_skills` (`id_skill`, `id_developer`) VALUES ('1', '1'),
('2', '1'),
('3', '2'),
('4', '2'),
('4', '3'),
('4', '4'),
('1', '5'),
('2', '5'),
('3', '5'),
('4', '6');




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

